######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 5 18:57:36 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qmlapplicationviewer
INCLUDEPATH += . qmlapplicationviewer

# Input
HEADERS += framecapture.h qmlapplicationviewer/qmlapplicationviewer.h
SOURCES += framecapture.cpp \
           main.cpp \
           qmlapplicationviewer/qmlapplicationviewer.cpp
